using Cervantes.Arquisoft.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace Cervantes.Arquisoft.Data.Seeds
{
    public class LocalitySeed : IEntityTypeConfiguration<Locality>
    {
        public void Configure(EntityTypeBuilder<Locality> builder)
        {
            builder.HasData(
                new Locality { LocalityId = 1, ProvinceId = 1, Description = "Buenos Aires" },
                new Locality { LocalityId = 2, ProvinceId = 1, Description = "La Plata" },
                new Locality { LocalityId = 3, ProvinceId = 1, Description = "Mar del Plata" },
                new Locality { LocalityId = 4, ProvinceId = 1, Description = "Bahía Blanca" },
                new Locality { LocalityId = 5, ProvinceId = 1, Description = "San Isidro" },
                new Locality { LocalityId = 6, ProvinceId = 1, Description = "Pilar" },
                new Locality { LocalityId = 7, ProvinceId = 1, Description = "Quilmes" },
                new Locality { LocalityId = 8, ProvinceId = 1, Description = "Morón" },
                new Locality { LocalityId = 9, ProvinceId = 1, Description = "Tandil" },
                new Locality { LocalityId = 10, ProvinceId = 1, Description = "Lomas de Zamora" },
                new Locality { LocalityId = 11, ProvinceId = 2, Description = "San Fernando del Valle de Catamarca" },
                new Locality { LocalityId = 12, ProvinceId = 2, Description = "Andalgalá" },
                new Locality { LocalityId = 13, ProvinceId = 2, Description = "Belén" },
                new Locality { LocalityId = 14, ProvinceId = 2, Description = "Santa María" },
                new Locality { LocalityId = 15, ProvinceId = 2, Description = "Recreo" },
                new Locality { LocalityId = 16, ProvinceId = 2, Description = "Fiambalá" },
                new Locality { LocalityId = 17, ProvinceId = 2, Description = "Tinogasta" },
                new Locality { LocalityId = 18, ProvinceId = 2, Description = "Saujil" },
                new Locality { LocalityId = 19, ProvinceId = 2, Description = "Aconquija" },
                new Locality { LocalityId = 20, ProvinceId = 2, Description = "Los Altos" },
                new Locality { LocalityId = 21, ProvinceId = 3, Description = "Resistencia" },
                new Locality { LocalityId = 22, ProvinceId = 3, Description = "Barranqueras" },
                new Locality { LocalityId = 23, ProvinceId = 3, Description = "Fontana" },
                new Locality { LocalityId = 24, ProvinceId = 3, Description = "Presidencia Roque Sáenz Peña" },
                new Locality { LocalityId = 25, ProvinceId = 3, Description = "Villa Ángela" },
                new Locality { LocalityId = 26, ProvinceId = 3, Description = "Charata" },
                new Locality { LocalityId = 27, ProvinceId = 3, Description = "General San Martín" },
                new Locality { LocalityId = 28, ProvinceId = 3, Description = "Juan José Castelli" },
                new Locality { LocalityId = 29, ProvinceId = 3, Description = "Quitilipi" },
                new Locality { LocalityId = 30, ProvinceId = 3, Description = "Machagai" },
                new Locality { LocalityId = 31, ProvinceId = 4, Description = "Rawson" },
                new Locality { LocalityId = 32, ProvinceId = 4, Description = "Comodoro Rivadavia" },
                new Locality { LocalityId = 33, ProvinceId = 4, Description = "Puerto Madryn" },
                new Locality { LocalityId = 34, ProvinceId = 4, Description = "Trelew" },
                new Locality { LocalityId = 35, ProvinceId = 4, Description = "Esquel" },
                new Locality { LocalityId = 36, ProvinceId = 4, Description = "Rada Tilly" },
                new Locality { LocalityId = 37, ProvinceId = 4, Description = "Gaiman" },
                new Locality { LocalityId = 38, ProvinceId = 4, Description = "Sarmiento" },
                new Locality { LocalityId = 39, ProvinceId = 4, Description = "Dolavon" },
                new Locality { LocalityId = 40, ProvinceId = 4, Description = "Gobernador Costa" },
                new Locality { LocalityId = 41, ProvinceId = 5, Description = "Córdoba" },
                new Locality { LocalityId = 42, ProvinceId = 5, Description = "Villa Carlos Paz" },
                new Locality { LocalityId = 43, ProvinceId = 5, Description = "Río Cuarto" },
                new Locality { LocalityId = 44, ProvinceId = 5, Description = "Alta Gracia" },
                new Locality { LocalityId = 45, ProvinceId = 5, Description = "San Francisco" },
                new Locality { LocalityId = 46, ProvinceId = 5, Description = "Villa María" },
                new Locality { LocalityId = 47, ProvinceId = 5, Description = "Jesús María" },
                new Locality { LocalityId = 48, ProvinceId = 5, Description = "Bell Ville" },
                new Locality { LocalityId = 49, ProvinceId = 5, Description = "Cosquín" },
                new Locality { LocalityId = 50, ProvinceId = 5, Description = "La Falda" },
                new Locality { LocalityId = 51, ProvinceId = 6, Description = "Corrientes" },
                new Locality { LocalityId = 52, ProvinceId = 6, Description = "Goya" },
                new Locality { LocalityId = 53, ProvinceId = 6, Description = "Mercedes" },
                new Locality { LocalityId = 54, ProvinceId = 6, Description = "Curuzú Cuatiá" },
                new Locality { LocalityId = 55, ProvinceId = 6, Description = "Bella Vista" },
                new Locality { LocalityId = 56, ProvinceId = 6, Description = "Esquina" },
                new Locality { LocalityId = 57, ProvinceId = 6, Description = "Ituzaingó" },
                new Locality { LocalityId = 58, ProvinceId = 6, Description = "Santo Tomé" },
                new Locality { LocalityId = 59, ProvinceId = 6, Description = "Monte Caseros" },
                new Locality { LocalityId = 60, ProvinceId = 6, Description = "Paso de los Libres" },
                new Locality { LocalityId = 61, ProvinceId = 7, Description = "Paraná" },
                new Locality { LocalityId = 62, ProvinceId = 7, Description = "Concordia" },
                new Locality { LocalityId = 63, ProvinceId = 7, Description = "Gualeguaychú" },
                new Locality { LocalityId = 64, ProvinceId = 7, Description = "Gualeguay" },
                new Locality { LocalityId = 65, ProvinceId = 7, Description = "Chajarí" },
                new Locality { LocalityId = 66, ProvinceId = 7, Description = "Villaguay" },
                new Locality { LocalityId = 67, ProvinceId = 7, Description = "Colón" },
                new Locality { LocalityId = 68, ProvinceId = 7, Description = "Victoria" },
                new Locality { LocalityId = 69, ProvinceId = 7, Description = "Diamante" },
                new Locality { LocalityId = 70, ProvinceId = 7, Description = "La Paz" },
                new Locality { LocalityId = 71, ProvinceId = 8, Description = "Formosa" },
                new Locality { LocalityId = 72, ProvinceId = 8, Description = "Clorinda" },
                new Locality { LocalityId = 73, ProvinceId = 8, Description = "Pirané" },
                new Locality { LocalityId = 74, ProvinceId = 8, Description = "El Colorado" },
                new Locality { LocalityId = 75, ProvinceId = 8, Description = "Las Lomitas" },
                new Locality { LocalityId = 76, ProvinceId = 8, Description = "Riacho He Hé" },
                new Locality { LocalityId = 77, ProvinceId = 8, Description = "Laguna Yema" },
                new Locality { LocalityId = 78, ProvinceId = 8, Description = "Ibarreta" },
                new Locality { LocalityId = 79, ProvinceId = 8, Description = "General Güemes" },
                new Locality { LocalityId = 80, ProvinceId = 8, Description = "San Martín 2" },
                new Locality { LocalityId = 81, ProvinceId = 9, Description = "San Salvador de Jujuy" },
                new Locality { LocalityId = 82, ProvinceId = 9, Description = "Palpalá" },
                new Locality { LocalityId = 83, ProvinceId = 9, Description = "San Pedro" },
                new Locality { LocalityId = 84, ProvinceId = 9, Description = "Libertador General San Martín" },
                new Locality { LocalityId = 85, ProvinceId = 9, Description = "Perico" },
                new Locality { LocalityId = 86, ProvinceId = 9, Description = "El Carmen" },
                new Locality { LocalityId = 87, ProvinceId = 9, Description = "Humahuaca" },
                new Locality { LocalityId = 88, ProvinceId = 9, Description = "La Quiaca" },
                new Locality { LocalityId = 89, ProvinceId = 9, Description = "Tilcara" },
                new Locality { LocalityId = 90, ProvinceId = 9, Description = "Abra Pampa" },
                new Locality { LocalityId = 91, ProvinceId = 10, Description = "Santa Rosa" },
                new Locality { LocalityId = 92, ProvinceId = 10, Description = "General Pico" },
                new Locality { LocalityId = 93, ProvinceId = 10, Description = "Toay" },
                new Locality { LocalityId = 94, ProvinceId = 10, Description = "Realicó" },
                new Locality { LocalityId = 95, ProvinceId = 10, Description = "Eduardo Castex" },
                new Locality { LocalityId = 96, ProvinceId = 10, Description = "General Acha" },
                new Locality { LocalityId = 97, ProvinceId = 10, Description = "25 de Mayo" },
                new Locality { LocalityId = 98, ProvinceId = 10, Description = "General Manuel J. Campos" },
                new Locality { LocalityId = 99, ProvinceId = 10, Description = "Catriló" },
                new Locality { LocalityId = 100, ProvinceId = 10, Description = "Macachín" },
                new Locality { LocalityId = 101, ProvinceId = 11, Description = "La Rioja" },
                new Locality { LocalityId = 102, ProvinceId = 11, Description = "Chilecito" },
                new Locality { LocalityId = 103, ProvinceId = 11, Description = "Chamical" },
                new Locality { LocalityId = 104, ProvinceId = 11, Description = "Famatina" },
                new Locality { LocalityId = 105, ProvinceId = 11, Description = "Chepes" },
                new Locality { LocalityId = 106, ProvinceId = 11, Description = "Arauco" },
                new Locality { LocalityId = 107, ProvinceId = 11, Description = "Olta" },
                new Locality { LocalityId = 108, ProvinceId = 11, Description = "Villa Unión" },
                new Locality { LocalityId = 109, ProvinceId = 11, Description = "Villa Castelli" },
                new Locality { LocalityId = 110, ProvinceId = 11, Description = "Sanagasta" },
                new Locality { LocalityId = 111, ProvinceId = 12, Description = "Mendoza" },
                new Locality { LocalityId = 112, ProvinceId = 12, Description = "San Rafael" },
                new Locality { LocalityId = 113, ProvinceId = 12, Description = "Godoy Cruz" },
                new Locality { LocalityId = 114, ProvinceId = 12, Description = "Luján de Cuyo" },
                new Locality { LocalityId = 115, ProvinceId = 12, Description = "Las Heras" },
                new Locality { LocalityId = 116, ProvinceId = 12, Description = "Maipú" },
                new Locality { LocalityId = 117, ProvinceId = 12, Description = "San Martín" },
                new Locality { LocalityId = 118, ProvinceId = 12, Description = "Malargüe" },
                new Locality { LocalityId = 119, ProvinceId = 12, Description = "Tunuyán" },
                new Locality { LocalityId = 120, ProvinceId = 12, Description = "General Alvear" },
                new Locality { LocalityId = 121, ProvinceId = 13, Description = "Posadas" },
                new Locality { LocalityId = 122, ProvinceId = 13, Description = "Eldorado" },
                new Locality { LocalityId = 123, ProvinceId = 13, Description = "Puerto Iguazú" },
                new Locality { LocalityId = 124, ProvinceId = 13, Description = "Oberá" },
                new Locality { LocalityId = 125, ProvinceId = 13, Description = "Apostoles" },
                new Locality { LocalityId = 126, ProvinceId = 13, Description = "San Vicente" },
                new Locality { LocalityId = 127, ProvinceId = 13, Description = "Alem" },
                new Locality { LocalityId = 128, ProvinceId = 13, Description = "Jardín América" },
                new Locality { LocalityId = 129, ProvinceId = 13, Description = "Montecarlo" },
                new Locality { LocalityId = 130, ProvinceId = 13, Description = "Puerto Rico" },
                new Locality { LocalityId = 131, ProvinceId = 14, Description = "Neuquén" },
                new Locality { LocalityId = 132, ProvinceId = 14, Description = "San Martín de los Andes" },
                new Locality { LocalityId = 133, ProvinceId = 14, Description = "Cutral Có" },
                new Locality { LocalityId = 134, ProvinceId = 14, Description = "Plottier" },
                new Locality { LocalityId = 135, ProvinceId = 14, Description = "Zapala" },
                new Locality { LocalityId = 136, ProvinceId = 14, Description = "Centenario" },
                new Locality { LocalityId = 137, ProvinceId = 14, Description = "Villa La Angostura" },
                new Locality { LocalityId = 138, ProvinceId = 14, Description = "Chos Malal" },
                new Locality { LocalityId = 139, ProvinceId = 14, Description = "Senillosa" },
                new Locality { LocalityId = 140, ProvinceId = 14, Description = "Rincón de los Sauces" },
                new Locality { LocalityId = 141, ProvinceId = 15, Description = "Viedma" },
                new Locality { LocalityId = 142, ProvinceId = 15, Description = "San Carlos de Bariloche" },
                new Locality { LocalityId = 143, ProvinceId = 15, Description = "General Roca" },
                new Locality { LocalityId = 144, ProvinceId = 15, Description = "Cipolletti" },
                new Locality { LocalityId = 145, ProvinceId = 15, Description = "Allen" },
                new Locality { LocalityId = 146, ProvinceId = 15, Description = "El Bolsón" },
                new Locality { LocalityId = 147, ProvinceId = 15, Description = "Ingeniero Jacobacci" },
                new Locality { LocalityId = 148, ProvinceId = 15, Description = "Villa Regina" },
                new Locality { LocalityId = 150, ProvinceId = 15, Description = "Choele Choel" },
                new Locality { LocalityId = 151, ProvinceId = 15, Description = "Cinco Saltos" },
                new Locality { LocalityId = 152, ProvinceId = 16, Description = "Salta" },
                new Locality { LocalityId = 153, ProvinceId = 16, Description = "San Ramón de la Nueva Orán" },
                new Locality { LocalityId = 154, ProvinceId = 16, Description = "General Güemes" },
                new Locality { LocalityId = 155, ProvinceId = 16, Description = "Tartagal" },
                new Locality { LocalityId = 156, ProvinceId = 16, Description = "Cafayate" },
                new Locality { LocalityId = 157, ProvinceId = 16, Description = "San Pedro de Jujuy" },
                new Locality { LocalityId = 158, ProvinceId = 16, Description = "Metán" },
                new Locality { LocalityId = 159, ProvinceId = 16, Description = "El Carril" },
                new Locality { LocalityId = 160, ProvinceId = 16, Description = "Rosario de la Frontera" },
                new Locality { LocalityId = 161, ProvinceId = 16, Description = "Chicoana" },
                new Locality { LocalityId = 162, ProvinceId = 17, Description = "San Juan" },
                new Locality { LocalityId = 163, ProvinceId = 17, Description = "Rawson" },
                new Locality { LocalityId = 164, ProvinceId = 17, Description = "Chimbas" },
                new Locality { LocalityId = 165, ProvinceId = 17, Description = "Pocito" },
                new Locality { LocalityId = 166, ProvinceId = 17, Description = "Rivadavia" },
                new Locality { LocalityId = 167, ProvinceId = 17, Description = "Santa Lucía" },
                new Locality { LocalityId = 168, ProvinceId = 17, Description = "Caucete" },
                new Locality { LocalityId = 169, ProvinceId = 17, Description = "Albardón" },
                new Locality { LocalityId = 170, ProvinceId = 17, Description = "Jáchal" },
                new Locality { LocalityId = 171, ProvinceId = 17, Description = "25 de Mayo" },
                new Locality { LocalityId = 172, ProvinceId = 18, Description = "San Luis" },
                new Locality { LocalityId = 173, ProvinceId = 18, Description = "Villa Mercedes" },
                new Locality { LocalityId = 174, ProvinceId = 18, Description = "San Francisco del Monte de Oro" },
                new Locality { LocalityId = 175, ProvinceId = 18, Description = "La Toma" },
                new Locality { LocalityId = 176, ProvinceId = 18, Description = "Justo Daract" },
                new Locality { LocalityId = 177, ProvinceId = 18, Description = "Merlo" },
                new Locality { LocalityId = 178, ProvinceId = 18, Description = "Santa Rosa del Conlara" },
                new Locality { LocalityId = 179, ProvinceId = 18, Description = "Naschel" },
                new Locality { LocalityId = 180, ProvinceId = 18, Description = "Quines" },
                new Locality { LocalityId = 181, ProvinceId = 18, Description = "Concarán" },
                new Locality { LocalityId = 182, ProvinceId = 19, Description = "Río Gallegos" },
                new Locality { LocalityId = 183, ProvinceId = 19, Description = "Caleta Olivia" },
                new Locality { LocalityId = 184, ProvinceId = 19, Description = "El Calafate" },
                new Locality { LocalityId = 185, ProvinceId = 19, Description = "Puerto Deseado" },
                new Locality { LocalityId = 186, ProvinceId = 19, Description = "Río Turbio" },
                new Locality { LocalityId = 187, ProvinceId = 19, Description = "28 de Noviembre" },
                new Locality { LocalityId = 188, ProvinceId = 19, Description = "Pico Truncado" },
                new Locality { LocalityId = 189, ProvinceId = 19, Description = "Las Heras" },
                new Locality { LocalityId = 190, ProvinceId = 19, Description = "Perito Moreno" },
                new Locality { LocalityId = 191, ProvinceId = 19, Description = "Gobernador Gregores" },
                new Locality { LocalityId = 192, ProvinceId = 20, Description = "Santa Fe" },
                new Locality { LocalityId = 193, ProvinceId = 20, Description = "Rosario" },
                new Locality { LocalityId = 194, ProvinceId = 20, Description = "Venado Tuerto" },
                new Locality { LocalityId = 195, ProvinceId = 20, Description = "Rafaela" },
                new Locality { LocalityId = 196, ProvinceId = 20, Description = "Reconquista" },
                new Locality { LocalityId = 197, ProvinceId = 21, Description = "Santiago del Estero" },
                new Locality { LocalityId = 198, ProvinceId = 21, Description = "La Banda" },
                new Locality { LocalityId = 199, ProvinceId = 21, Description = "Termas de Río Hondo" },
                new Locality { LocalityId = 200, ProvinceId = 21, Description = "Añatuya" },
                new Locality { LocalityId = 201, ProvinceId = 21, Description = "Fernández" },
                new Locality { LocalityId = 202, ProvinceId = 21, Description = "Clodomira" },
                new Locality { LocalityId = 203, ProvinceId = 21, Description = "Frías" },
                new Locality { LocalityId = 204, ProvinceId = 21, Description = "Loreto" },
                new Locality { LocalityId = 205, ProvinceId = 21, Description = "Suncho Corral" },
                new Locality { LocalityId = 206, ProvinceId = 21, Description = "Beltrán" },
                new Locality { LocalityId = 207, ProvinceId = 22, Description = "Ushuaia" },
                new Locality { LocalityId = 208, ProvinceId = 22, Description = "Río Grande" },
                new Locality { LocalityId = 209, ProvinceId = 22, Description = "Tolhuin" },
                new Locality { LocalityId = 210, ProvinceId = 22, Description = "Puerto Almanza" },
                new Locality { LocalityId = 211, ProvinceId = 22, Description = "San Julián" },
                new Locality { LocalityId = 212, ProvinceId = 22, Description = "Puerto Williams" },
                new Locality { LocalityId = 213, ProvinceId = 22, Description = "Puerto Toro" },
                new Locality { LocalityId = 214, ProvinceId = 22, Description = "Puerto Yartou" },
                new Locality { LocalityId = 215, ProvinceId = 22, Description = "Caleta María" },
                new Locality { LocalityId = 216, ProvinceId = 22, Description = "Puerto Roballo" },
                new Locality { LocalityId = 217, ProvinceId = 23, Description = "San Miguel de Tucumán" },
                new Locality { LocalityId = 218, ProvinceId = 23, Description = "Yerba Buena" },
                new Locality { LocalityId = 219, ProvinceId = 23, Description = "Banda del Río Salí" },
                new Locality { LocalityId = 220, ProvinceId = 23, Description = "Concepción" },
                new Locality { LocalityId = 221, ProvinceId = 23, Description = "Aguilares" },
                new Locality { LocalityId = 222, ProvinceId = 23, Description = "Tafí Viejo" },
                new Locality { LocalityId = 223, ProvinceId = 23, Description = "Famaillá" },
                new Locality { LocalityId = 224, ProvinceId = 23, Description = "Tafí del Valle" },
                new Locality { LocalityId = 225, ProvinceId = 23, Description = "Monteros" },
                new Locality { LocalityId = 226, ProvinceId = 23, Description = "Lules" }

        );

    }
    }
}